"""initial schema

Revision ID: 171587e9a254
Revises: 
Create Date: 2026-09-13 14:43:28.042290
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '171587e9a254'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('repository_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('vulnerability_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_url', sa.Text(), nullable=True),
    sa.Column('affected', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vulnerability_id')
    )
    op.create_index(op.f('ix_vulnerabilities_identifier'), 'vulnerabilities', ['identifier'], unique=True)
    op.create_table('analyses',
    sa.Column('analysis_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_risk', sa.String(length=20), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_analyses_repository_id'), 'analyses', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('components',
    sa.Column('component_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('component_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id'),
    sa.UniqueConstraint('repository_id', 'path', name='uq_component_repo_path')
    )
    op.create_index(op.f('ix_components_repository_id'), 'components', ['repository_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('dependency_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('version_spec', sa.String(length=255), nullable=True),
    sa.Column('ecosystem', sa.String(length=30), nullable=False),
    sa.Column('direct_or_transitive', sa.String(length=20), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('vulnerability_status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.analysis_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dependency_id'),
    sa.UniqueConstraint('analysis_id', 'ecosystem', 'package_name', 'version', 'source_file', name='uq_dependency_identity')
    )
    op.create_index(op.f('ix_dependencies_analysis_id'), 'dependencies', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_dependencies_repository_id'), 'dependencies', ['repository_id'], unique=False)
    op.create_index('ix_dependency_pkg', 'dependencies', ['ecosystem', 'package_name'], unique=False)
    op.create_table('dependency_relations',
    sa.Column('relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_dependency_id', sa.Integer(), nullable=False),
    sa.Column('child_dependency_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['child_dependency_id'], ['dependencies.dependency_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_dependency_id'], ['dependencies.dependency_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('parent_dependency_id', 'child_dependency_id', name='uq_dependency_relation')
    )
    op.create_index(op.f('ix_dependency_relations_child_dependency_id'), 'dependency_relations', ['child_dependency_id'], unique=False)
    op.create_index(op.f('ix_dependency_relations_parent_dependency_id'), 'dependency_relations', ['parent_dependency_id'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('affected_components', sa.JSON(), nullable=True),
    sa.Column('usage_evidence', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('ai_results', sa.JSON(), nullable=True),
    sa.Column('ai_status', sa.String(length=20), nullable=False),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.analysis_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.dependency_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.vulnerability_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id'),
    sa.UniqueConstraint('analysis_id', 'dependency_id', 'vulnerability_id', name='uq_finding_identity')
    )
    op.create_index(op.f('ix_findings_analysis_id'), 'findings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_findings_dependency_id'), 'findings', ['dependency_id'], unique=False)
    op.create_index(op.f('ix_findings_risk_level'), 'findings', ['risk_level'], unique=False)
    op.create_index(op.f('ix_findings_vulnerability_id'), 'findings', ['vulnerability_id'], unique=False)
    op.create_table('remediations',
    sa.Column('remediation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.String(length=100), nullable=True),
    sa.Column('recommended_version', sa.String(length=100), nullable=True),
    sa.Column('alternative_package', sa.String(length=255), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('ai_result', sa.JSON(), nullable=True),
    sa.Column('proposed_change', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('remediation_id')
    )
    op.create_index(op.f('ix_remediations_finding_id'), 'remediations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediations_status'), 'remediations', ['status'], unique=False)
    op.create_table('pull_requests',
    sa.Column('pr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.remediation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pr_id')
    )
    op.create_index(op.f('ix_pull_requests_remediation_id'), 'pull_requests', ['remediation_id'], unique=False)
    op.create_table('validations',
    sa.Column('validation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('build_status', sa.String(length=20), nullable=False),
    sa.Column('test_status', sa.String(length=20), nullable=False),
    sa.Column('security_scan_status', sa.String(length=20), nullable=False),
    sa.Column('overall_result', sa.String(length=20), nullable=False),
    sa.Column('logs_path', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.remediation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_index(op.f('ix_validations_remediation_id'), 'validations', ['remediation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validations_remediation_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_pull_requests_remediation_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_remediations_status'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_finding_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_findings_vulnerability_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_risk_level'), table_name='findings')
    op.drop_index(op.f('ix_findings_dependency_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_analysis_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_dependency_relations_parent_dependency_id'), table_name='dependency_relations')
    op.drop_index(op.f('ix_dependency_relations_child_dependency_id'), table_name='dependency_relations')
    op.drop_table('dependency_relations')
    op.drop_index('ix_dependency_pkg', table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_repository_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_analysis_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_components_repository_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_repository_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_vulnerabilities_identifier'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
