"""job heartbeats and repository ingestion status

Revision ID: 87d49b40789f
Revises: 171587e9a254
Create Date: 2026-09-14 14:54:41.598612
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '87d49b40789f'
down_revision = '171587e9a254'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('findings', sa.Column('ai_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('remediations', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('status', sa.String(length=20), server_default='READY', nullable=False))
    op.add_column('repositories', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('validations', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validations', 'heartbeat_at')
    op.drop_column('repositories', 'error_message')
    op.drop_column('repositories', 'status')
    op.drop_column('remediations', 'heartbeat_at')
    op.drop_column('findings', 'ai_updated_at')
    op.drop_column('analyses', 'heartbeat_at')
    # ### end Alembic commands ###
