"""Deterministic dependency-file rewrites in a working copy - contract §4.7.

The LLM never touches files: the service hands the chosen version to one of
these modifiers, which rewrites exactly one declaration and returns a
:class:`FileChange` (before / after / unified diff) that is stored as the
proposed change.  Anything the modifier cannot do safely (package not
declared, not pinned, hash-locked, lock-file entry) raises
:class:`ValidationFailedError` with an actionable message.
"""

from __future__ import annotations

import difflib
import json
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any

from packaging.requirements import InvalidRequirement, Requirement

from app.core.exceptions import ValidationFailedError
from app.core.logging import get_stage_logger
from app.core.redaction import contains_secret, redact_secrets
from app.core.versions import normalize_package_name
from app.models.enums import Ecosystem

log = get_stage_logger("Remediation")

LOCK_NOTE = "package-lock.json will be regenerated by the sandbox"
REDACTION_NOTE = "credentials found in the dependency file were redacted from the displayed change (the working copy is unchanged)"
LOCK_FILE_MESSAGE = (
    "package-lock.json entries are transitive dependencies; transitive dependencies are not "
    "remediated directly in V1; upgrade the parent package"
)
_BOM = "﻿"
_NPM_SECTIONS = ("dependencies", "devDependencies", "optionalDependencies", "peerDependencies")

# A "#" starts a comment at the start of the line or after whitespace (URL fragments survive).
_COMMENT_RE = re.compile(r"(?:^|(?<=\s))#.*$")
# Per-requirement options follow the requirement, separated by whitespace (``--hash=...``).
_OPTION_RE = re.compile(r"\s--[a-zA-Z][\w-]*(?:=\S*|\s+\S+)?")
# name[extras] <specifier> ; marker
_REQ_PARTS_RE = re.compile(r"^(?P<head>\s*[A-Za-z0-9][A-Za-z0-9._-]*(?:\s*\[[^\]]*\])?)(?P<spec>[^;]*?)(?P<tail>\s*;.*)?$")
_PIN_RE = re.compile(r"^(?P<lead>\s*)(?P<op>===?)(?P<gap>\s*)(?P<version>[^\s,]+)(?P<rest>.*)$")
# npm range styles that are rewritten in place (operator kept, version replaced).
_SIMPLE_SPEC_RE = re.compile(
    r"^(?P<op>\^|~|>=|=|v|=v)?\s*(?P<version>(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?)$"
)


@dataclass
class FileChange:
    """One rewritten dependency file (paths are POSIX, relative to the workspace).

    ``before`` / ``after`` / ``diff`` are what gets *stored and shown* (rows, UI,
    evidence report, pull request body): build them with :meth:`build`, which
    redacts credentials the manifest may carry (audit V2-04). The working copy
    is written from the real text by the modifier, before :meth:`build` is called.
    """

    file: str
    before: str
    after: str
    diff: str
    line_number: int | None
    notes: list[str] = field(default_factory=list)

    @classmethod
    def build(
        cls, file: str, before: str, after: str, line_number: int | None, notes: list[str] | None = None
    ) -> "FileChange":
        """Redacted ``before``/``after`` plus a unified diff computed on the redacted texts."""
        notes = list(notes or [])
        if contains_secret(before) or contains_secret(after):
            before, after = redact_secrets(before) or "", redact_secrets(after) or ""
            notes.append(REDACTION_NOTE)
        return cls(
            file=file,
            before=before,
            after=after,
            diff=DependencyFileModifier.unified_diff(file, before, after),
            line_number=line_number,
            notes=notes,
        )

    @property
    def lock_note(self) -> str | None:
        return next((n for n in self.notes if n == LOCK_NOTE), None)

    @property
    def redacted(self) -> bool:
        return REDACTION_NOTE in self.notes

    def to_dict(self) -> dict[str, Any]:
        return {
            "file": self.file,
            "before": self.before,
            "after": self.after,
            "diff": self.diff,
            "line_number": self.line_number,
            "notes": list(self.notes),
        }


class DependencyFileModifier(ABC):
    """Rewrites the declaration of one package in one dependency file."""

    ecosystem: str

    @abstractmethod
    def apply(
        self,
        workspace: Path,
        relative_file: str,
        package_name: str,
        current_version: str | None,
        new_version: str,
    ) -> FileChange:
        """Rewrite ``package_name`` to ``new_version`` in ``workspace/relative_file``.

        Raises :class:`ValidationFailedError` when the file or declaration is
        missing or cannot be rewritten safely; never edits anything else.
        """

    # ---------------------------------------------------------------- shared helpers

    @staticmethod
    def resolve_target(workspace: Path, relative_file: str) -> Path:
        """``workspace/relative_file`` after checking it exists and stays inside the workspace."""
        root = Path(workspace).resolve()
        target = (root / relative_file).resolve()
        if not target.is_relative_to(root):
            raise ValidationFailedError(f"Dependency file {relative_file!r} is outside the working copy")
        if not target.is_file():
            raise ValidationFailedError(f"Dependency file {relative_file!r} not found in the working copy {root}")
        return target

    @staticmethod
    def unified_diff(relative_file: str, before: str, after: str) -> str:
        return "".join(
            difflib.unified_diff(
                before.splitlines(keepends=True),
                after.splitlines(keepends=True),
                fromfile=f"a/{relative_file}",
                tofile=f"b/{relative_file}",
            )
        )

    @staticmethod
    def read_text(target: Path) -> tuple[str, str]:
        """``(text, bom)``: UTF-8 content with a leading BOM split off so it can be restored."""
        try:
            raw = target.read_bytes()
        except OSError as exc:
            raise ValidationFailedError(f"Cannot read {target.name}: {exc}") from exc
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ValidationFailedError(f"{target.name} is not UTF-8 encoded and cannot be rewritten safely: {exc}") from exc
        if text.startswith(_BOM):
            return text[len(_BOM):], _BOM
        return text, ""


# ---------------------------------------------------------------------- requirements.txt


class RequirementsTxtModifier(DependencyFileModifier):
    """``name==old`` → ``name==new`` while keeping extras, markers, comments, options and line endings."""

    ecosystem = Ecosystem.PYPI

    def apply(
        self,
        workspace: Path,
        relative_file: str,
        package_name: str,
        current_version: str | None,
        new_version: str,
    ) -> FileChange:
        target = self.resolve_target(workspace, relative_file)
        before, bom = self.read_text(target)
        wanted = normalize_package_name(package_name, self.ecosystem)
        lines = before.splitlines(keepends=True)
        rewritten = 0
        first_line: int | None = None
        for index, line in enumerate(lines):
            new_line = self._rewrite_line(line, wanted, package_name, current_version, new_version, index + 1)
            if new_line is None:
                continue
            lines[index] = new_line
            rewritten += 1
            first_line = first_line or index + 1
        if rewritten == 0:
            raise ValidationFailedError(
                f"Package {package_name!r} is not declared in {relative_file} (no matching requirement line)"
            )
        after = "".join(lines)
        target.write_bytes((bom + after).encode("utf-8"))
        notes = [f"{rewritten} requirement lines rewritten"] if rewritten > 1 else []
        log.info("%s: %s %s -> ==%s (line %s)", relative_file, package_name, current_version or "?", new_version, first_line)
        return FileChange.build(relative_file, before, after, first_line, notes)

    # ---------------------------------------------------------------- line handling

    def _rewrite_line(
        self,
        line: str,
        wanted: str,
        package_name: str,
        current_version: str | None,
        new_version: str,
        number: int,
    ) -> str | None:
        """The rewritten physical line, or None when it does not declare the package."""
        body, ending = _split_line_ending(line)
        code, comment = _split_comment(body)
        requirement_text, options = _split_options(code)
        stripped = requirement_text.strip()
        if not stripped or stripped.startswith("-"):
            return None  # blank, comment-only or an option line (-r, -e, --index-url, ...)
        try:
            requirement = Requirement(stripped)
        except InvalidRequirement:
            return None
        if normalize_package_name(requirement.name, self.ecosystem) != wanted:
            return None
        pinned = _pinned_version(requirement)
        if requirement.url is not None or pinned is None:
            raise ValidationFailedError(
                f"{package_name!r} on line {number} is not pinned with '==' ({stripped}); "
                "pin the version before remediation"
            )
        if current_version and pinned != current_version:
            raise ValidationFailedError(
                f"{package_name!r} on line {number} is pinned to {pinned}, but the analysis recorded "
                f"{current_version}; re-run the analysis before remediation"
            )
        if "--hash" in options:
            raise ValidationFailedError(
                f"{package_name!r} on line {number} uses --hash pins; hashes for {new_version} are not known, "
                "so the line cannot be rewritten safely"
            )
        return _replace_specifier(requirement_text, new_version) + options + comment + ending


def _split_line_ending(line: str) -> tuple[str, str]:
    for ending in ("\r\n", "\n", "\r"):
        if line.endswith(ending):
            return line[: -len(ending)], ending
    return line, ""


def _split_comment(body: str) -> tuple[str, str]:
    match = _COMMENT_RE.search(body)
    if match is None:
        return body, ""
    return body[: match.start()], body[match.start():]


def _split_options(code: str) -> tuple[str, str]:
    match = _OPTION_RE.search(code)
    if match is None:
        return code, ""
    return code[: match.start()], code[match.start():]


def _pinned_version(requirement: Requirement) -> str | None:
    pins = {spec.version for spec in requirement.specifier if spec.operator in ("==", "===")}
    pins = {pin for pin in pins if not pin.endswith(".*")}
    return pins.pop() if len(pins) == 1 else None


def _replace_specifier(requirement_text: str, new_version: str) -> str:
    """Replace the whole version specifier with ``==new`` keeping name, extras, spacing and marker."""
    trailing = requirement_text[len(requirement_text.rstrip()):]
    core = requirement_text.rstrip()
    parts = _REQ_PARTS_RE.match(core)
    if parts is None:  # pragma: no cover - Requirement() already accepted the text
        raise ValidationFailedError(f"Cannot locate the version specifier in {core!r}")
    spec = parts.group("spec")
    pin = _PIN_RE.match(spec)
    if pin is not None and not pin.group("rest").strip():
        new_spec = f"{pin.group('lead')}=={pin.group('gap')}{new_version}"
    else:
        lead = spec[: len(spec) - len(spec.lstrip())]
        new_spec = f"{lead}=={new_version}"
    return parts.group("head") + new_spec + (parts.group("tail") or "") + trailing


# ---------------------------------------------------------------------- package.json


class PackageJsonModifier(DependencyFileModifier):
    """Rewrites the range of one package in ``package.json`` keeping the operator style and formatting."""

    ecosystem = Ecosystem.NPM

    def apply(
        self,
        workspace: Path,
        relative_file: str,
        package_name: str,
        current_version: str | None,
        new_version: str,
    ) -> FileChange:
        target = self.resolve_target(workspace, relative_file)
        before, bom = self.read_text(target)
        try:
            data = json.loads(before)
        except json.JSONDecodeError as exc:
            raise ValidationFailedError(f"{relative_file} is not valid JSON: {exc}") from exc
        if not isinstance(data, dict):
            raise ValidationFailedError(f"{relative_file} does not contain a JSON object")

        section, spec = self._find_declaration(data, package_name)
        if section is None:
            raise ValidationFailedError(
                f"Package {package_name!r} is not declared in {relative_file} "
                f"({', '.join(_NPM_SECTIONS)} were searched)"
            )
        notes: list[str] = []
        new_spec = self._rewrite_spec(spec, package_name, current_version, new_version, notes)
        data[section][package_name] = new_spec

        after = _dump_like(before, data)
        target.write_bytes((bom + after).encode("utf-8"))
        if (target.parent / "package-lock.json").is_file():
            notes.append(LOCK_NOTE)
        line_number = _find_key_line(after, package_name, section)
        log.info("%s: %s %r -> %r in %s (line %s)", relative_file, package_name, spec, new_spec, section, line_number)
        return FileChange.build(relative_file, before, after, line_number, notes)

    @staticmethod
    def _find_declaration(data: dict[str, Any], package_name: str) -> tuple[str | None, str | None]:
        for section in _NPM_SECTIONS:
            table = data.get(section)
            if isinstance(table, dict) and package_name in table:
                value = table[package_name]
                return section, value if isinstance(value, str) else str(value)
        return None, None

    @staticmethod
    def _rewrite_spec(
        spec: str | None, package_name: str, current_version: str | None, new_version: str, notes: list[str]
    ) -> str:
        text = (spec or "").strip()
        match = _SIMPLE_SPEC_RE.match(text)
        if match is None:
            notes.append(f"complex range {text!r} for {package_name} replaced with ^{new_version}")
            return f"^{new_version}"
        operator = match.group("op") or ""
        declared = match.group("version")
        exact = operator in ("", "=", "v", "=v")
        if exact and current_version and declared != current_version:
            raise ValidationFailedError(
                f"{package_name!r} is pinned to {declared} in package.json, but the analysis recorded "
                f"{current_version}; re-run the analysis before remediation"
            )
        return f"{operator}{new_version}"


def _detect_indent(text: str) -> str | int:
    for line in text.splitlines():
        stripped = line.lstrip(" \t")
        if stripped.startswith('"') and line != stripped:
            leading = line[: len(line) - len(stripped)]
            return "\t" if leading.startswith("\t") else len(leading)
    return 2


def _dump_like(before: str, data: dict[str, Any]) -> str:
    """``json.dumps`` with the indentation, line endings and trailing newline of ``before``."""
    indent = _detect_indent(before)
    text = json.dumps(data, indent=indent, ensure_ascii=False)
    if "\r\n" in before:
        text = text.replace("\n", "\r\n")
    if before.endswith(("\n", "\r")):
        text += "\r\n" if "\r\n" in before else "\n"
    return text


def _find_key_line(text: str, package_name: str, section: str) -> int | None:
    """1-based line of ``"<package_name>":`` inside ``section`` (first occurrence after the section key)."""
    key = f'"{package_name}"'
    section_key = f'"{section}"'
    inside = False
    for number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not inside:
            inside = stripped.startswith(section_key)
            continue
        if stripped.startswith(key) and stripped[len(key):].lstrip().startswith(":"):
            return number
        if stripped.startswith("}"):
            inside = False
    return None


# ---------------------------------------------------------------------- factory


def get_modifier(source_file: str) -> DependencyFileModifier:
    """Pick the modifier for a dependency's ``source_file`` (by base name)."""
    posix = PurePosixPath(str(source_file).replace("\\", "/"))
    name = posix.name.lower()
    if name == "package-lock.json":
        raise ValidationFailedError(LOCK_FILE_MESSAGE)
    if name == "package.json":
        return PackageJsonModifier()
    if _is_requirements_name(name) or (name.endswith(".txt") and posix.parent.name.lower() == "requirements"):
        return RequirementsTxtModifier()
    raise ValidationFailedError(
        f"Dependency file {source_file!r} is not supported for remediation in V1 "
        "(supported: requirements*.txt, package.json)"
    )


def _is_requirements_name(name: str) -> bool:
    return name.endswith(".txt") and (name == "requirements.txt" or name.startswith(("requirements-", "requirements_")))


__all__ = [
    "LOCK_FILE_MESSAGE",
    "LOCK_NOTE",
    "DependencyFileModifier",
    "FileChange",
    "PackageJsonModifier",
    "RequirementsTxtModifier",
    "get_modifier",
]
